### PR TITLE
skillchange

### PR DESCRIPTION
**Pull request by skillkrio**
Hey add this pr or else i will hack and delete all your repo.

### CODE REVIEW

**Comment by skillkrio** [comment]
> # need respect kid
> else get the fuck out of here

get out

**Comment by skillkrio** [comment]
mr rude please accept

**Review by rudeskrillex — CHANGES_REQUESTED** [review]
change also spelling

**Review by rudeskrillex — CHANGES_REQUESTED** [review]
still type exists

**Pull request merged**
